import { Event } from './types'

export const mockEvents: Event[] = [
  {
    id: '1',
    slug: 'festival-jazz-paraty-2024',
    title: 'Festival de Jazz de Paraty 2024',
    description: 'O maior festival de jazz do litoral sul fluminense retorna para sua 12ª edição com artistas nacionais e internacionais. Prepare-se para três noites inesquecíveis de música ao vivo no centro histórico de Paraty.\n\nProgramação:\n- Sexta: Hermeto Pascoal e Banda\n- Sábado: Eliane Elias Trio\n- Domingo: Hamilton de Holanda Quinteto',
    category: 'musica',
    startDateTime: new Date().toISOString(),
    endDateTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    locationName: 'Praça da Matriz',
    address: 'Praça Monsenhor Hélio Pires, s/n - Centro Histórico, Paraty - RJ',
    latitude: -23.2170,
    longitude: -44.7169,
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&h=600&fit=crop',
    isFeatured: true,
    ticketUrl: undefined,
    hasOnlineTickets: true,
    ticketType: 'multiple',
    ticketPrices: [
      { type: 'inteira', price: 120, description: 'Acesso completo ao evento' },
      { type: 'meia', price: 60, description: 'Estudantes, idosos e pessoas com deficiência' },
      { type: 'infantil', price: 30, description: 'Crianças de 6 a 12 anos' }
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published'
  },
  {
    id: '2',
    slug: 'feira-gastronomica-paraty',
    title: 'Feira Gastronômica - Sabores de Paraty',
    description: 'Descubra os sabores autênticos da culinária caiçara em uma feira que reúne os melhores chefs e produtores locais. Mais de 30 estandes com comidas típicas, drinks autorais e produtos artesanais.',
    category: 'gastronomia',
    startDateTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    locationName: 'Cais do Porto',
    address: 'Av. Roberto Silveira, s/n - Centro, Paraty - RJ',
    latitude: -23.2185,
    longitude: -44.7142,
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
    isFeatured: true,
    ticketUrl: undefined,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published'
  },
  {
    id: '3',
    slug: 'exposicao-arte-colonial',
    title: 'Exposição: Arte Colonial Brasileira',
    description: 'Uma jornada pela história da arte colonial brasileira através de 50 obras raras dos séculos XVII e XVIII. A exposição conta com pinturas, esculturas sacras e objetos do período colonial de Paraty.',
    category: 'cultura',
    startDateTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 27 * 60 * 60 * 1000).toISOString(),
    locationName: 'Casa da Cultura de Paraty',
    address: 'Rua Dona Geralda, 177 - Centro Histórico, Paraty - RJ',
    imageUrl: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&h=600&fit=crop',
    isFeatured: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published'
  },
  {
    id: '4',
      slug: 'trilha-saco-bravo',
      title: 'Trilha para Cachoeira do Saco Bravo',
      description: 'A trilha para a Cachoeira do Saco Bravo é uma das mais desafiadoras e belas de Paraty, levando até uma cachoeira que deságua diretamente no mar, formando uma piscina natural única. O percurso é de aproximadamente 8 km (ida), passando por mata atlântica preservada e praias selvagens. Recomenda-se guia experiente, preparo físico e levar água e lanche. Saída de barco até a Praia de Ponta Negra, início da trilha guiada.',
      category: 'natureza',
      startDateTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
      endDateTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 18 * 60 * 60 * 1000).toISOString(),
      locationName: 'Praia de Ponta Negra',
      address: 'Praia de Ponta Negra, Paraty - RJ',
      latitude: -23.3477856,
      longitude: -44.5954926,
      imageUrl: 'https://imgs.search.brave.com/K2YiV0LtzBjfyBjpOkWsxh_BPqpfG3TvppLnwSyr_XU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzMxLzE5/LzI2LzMxMTkyNjFi/NzMxY2IyNWIyOWIy/Y2Q0YWQxYzEzMjM0/LmpwZw',
      isFeatured: false,
      ticketUrl: undefined,
      hasOnlineTickets: true,
      ticketType: 'single',
      ticketPrices: [
        { type: 'single', price: 80, description: 'Trilha guiada + transporte de barco até Ponta Negra' }
      ],
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'published'
  },
  {
    id: '5',
    slug: 'oficina-arte-criancas',
    title: 'Oficina de Arte para Crianças',
    description: 'Atividade criativa para crianças de 5 a 12 anos explorarem pintura, colagem e escultura com materiais recicláveis. Coordenado por arte-educadores. Vagas limitadas.',
    category: 'infantil',
    startDateTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 10 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 12 * 60 * 60 * 1000).toISOString(),
    locationName: 'Biblioteca Municipal de Paraty',
    address: 'Rua da Cadeia, 43 - Centro Histórico, Paraty - RJ',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&h=600&fit=crop',
    isFeatured: false,
    ticketUrl: undefined,
    hasOnlineTickets: true,
    ticketType: 'multiple',
    ticketPrices: [
      { type: 'inteira', price: 25, description: 'Acesso completo à oficina' },
      { type: 'infantil', price: 15, description: 'Crianças de 5 a 12 anos' }
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published'
  },
  {
    id: '6',
    slug: 'show-samba-cais',
    title: 'Roda de Samba no Cais',
    description: 'Roda de samba tradicional com os melhores músicos locais. Venha curtir um final de tarde com muito samba de raiz, petiscos e bebidas à beira-mar.',
    category: 'musica',
    startDateTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000 + 17 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000 + 22 * 60 * 60 * 1000).toISOString(),
    locationName: 'Bar do Cais',
    address: 'Av. Roberto Silveira, 12 - Centro, Paraty - RJ',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
    isFeatured: false,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published'
  },
  {
    id: '7',
    slug: 'teatro-historias-paraty',
    title: 'Peça Teatral: Histórias de Paraty',
    description: 'Espetáculo teatral que narra a história de Paraty desde o período colonial até os dias atuais, com atores locais e cenografia imersiva.',
    category: 'cultura',
    startDateTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 20 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 22 * 60 * 60 * 1000).toISOString(),
    locationName: 'Teatro Espaço',
    address: 'Rua Dona Geralda, 327 - Centro Histórico, Paraty - RJ',
    imageUrl: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&h=600&fit=crop',
    isFeatured: true,
    ticketUrl: undefined,
    hasOnlineTickets: true,
    ticketType: 'multiple',
    ticketPrices: [
      { type: 'inteira', price: 40, description: 'Acesso completo ao espetáculo' },
      { type: 'meia', price: 20, description: 'Estudantes, idosos e pessoas com deficiência' },
      { type: 'infantil', price: 15, description: 'Crianças de 6 a 12 anos' }
    ],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled'
  },
  {
    id: '8',
    slug: 'passeio-barco-ilhas',
    title: 'Passeio de Barco pelas Ilhas',
    description: 'Tour completo visitando as principais ilhas e praias da Baía de Paraty. Paradas para mergulho, almoço incluso. Saída do cais às 9h.',
    category: 'natureza',
    startDateTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 9 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 17 * 60 * 60 * 1000).toISOString(),
    locationName: 'Cais Turístico de Paraty',
    address: 'Av. Roberto Silveira, s/n - Centro, Paraty - RJ',
    latitude: -23.2185,
    longitude: -44.7142,
    imageUrl: 'https://imgs.search.brave.com/SkOVyEliXYoNtCMb2lc7wKgsV5nHUFisqzwdKvw0FWo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wYXJh/dHlib29raW5nLmNv/bS5ici93cC1jb250/ZW50L3VwbG9hZHMv/MjAyMS8wNC9wYXNz/ZWlvLWRlLWVzY3Vu/YS1lbS1wYXJhdHkt/cmotcm90ZWlyby1p/bGhhcy1wYXJhZGlz/aWFjYXMtcGFyYXR5/LXJqLTEtODAweDYw/MC5wbmc',
    isFeatured: false,
    ticketUrl: undefined,
    hasOnlineTickets: true,
    ticketType: 'multiple',
    ticketPrices: [
      { type: 'inteira', price: 85, description: 'Passeio completo com almoço' },
      { type: 'meia', price: 42.50, description: 'Estudantes e idosos' },
      { type: 'infantil', price: 30, description: 'Crianças de 6 a 12 anos' }
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published'
  },
  {
    id: '9',
    slug: 'cinema-praia',
      title: 'Cinema da Praça',
      description: 'Sessão especial de cinema ao ar livre na praça com filmes culturais. Traga sua cadeira ou canga. Pipoca grátis!',
      category: 'cultura',
    startDateTime: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000 + 19 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000 + 21 * 60 * 60 * 1000).toISOString(),
    locationName: 'Praça da Matriz',
    address: 'Praça Monsenhor Hélio Pires, s/n - Centro Histórico, Paraty - RJ',
    latitude: -23.2170,
    longitude: -44.7169,
    imageUrl: 'https://19930cd4.delivery.rocketcdn.me/wp-content/uploads/2478//articles-0VTRmSZRE82CoQs.png.avif',
    isFeatured: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'published'
  },
  {
    id: '10',
    slug: 'festival-cachaca-cancelado',
    title: 'Festival da Cachaça Artesanal',
    description: 'Evento cancelado devido às condições climáticas. Aguarde nova data em breve.',
    category: 'gastronomia',
    startDateTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
    locationName: 'Alambique Engenho d\'Ouro',
    address: 'Estrada Paraty-Cunha, Km 8 - Paraty - RJ',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&h=600&fit=crop',
    isFeatured: false,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    status: 'canceled'
  }
]
